--// This file was created by XHider v1.2 [https://discord.gg/hATuHQaQRb]

local fenv = getfenv()
local _ = fenv.gbwAqNHkCyuGXV
local _ = fenv["1rWPMaHPHe16d"]
local _ = fenv.hfboynkq5TwSv3
local _ = fenv.GrHHRx3EAy1Zag
local UserInputService = game:GetService("UserInputService")
local Players = game:GetService("Players")
local Workspace = game:GetService("Workspace")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")
local _v1 = Players.LocalPlayer:GetMouse()
local gui = Instance.new("ScreenGui")
gui.Name = "THG2_Wallhop"
local playergui = Players.LocalPlayer:WaitForChild("PlayerGui")
gui.Parent = playergui
gui.ResetOnSpawn = false
gui.DisplayOrder = 9999
local _v2 = Instance.new("Frame", gui)
_v2.Size = UDim2.new(0, 150, 0, 140)
_v2.Position = UDim2.new(1, -160, 0, 10)
_v2.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
_v2.BackgroundTransparency = 0.5
local _v3 = Instance.new("UICorner", _v2)
_v3.CornerRadius = UDim.new(0, 8)
local _v4 = Instance.new("UIStroke", _v2)
_v4.Color = Color3.fromRGB(255, 255, 255)
local _v5 = Instance.new("UIListLayout", _v2)
_v5.Padding = UDim.new(0, 1)
_v5.HorizontalAlignment = Enum.HorizontalAlignment.Center
local _v6 = Instance.new("TextLabel", _v2)
_v6.Size = UDim2.new(1, 0, 0, 22)
_v6.BackgroundTransparency = 1
_v6.Font = Enum.Font.GothamBold
_v6.TextSize = 10
_v6.Text = "WallHop: OFF"
_v6.TextColor3 = Color3.fromRGB(231, 76, 60)
local _ = fenv.TfX2ysc9vjHr
local _v7 = Instance.new("TextLabel", _v2)
_v7.Size = UDim2.new(1, 0, 0, 22)
_v7.BackgroundTransparency = 1
_v7.Font = Enum.Font.GothamBold
_v7.TextSize = 10
_v7.Text = "Auto Seam: OFF"
_v7.TextColor3 = Color3.fromRGB(231, 76, 60)
local _v8 = Instance.new("TextLabel", _v2)
_v8.Size = UDim2.new(1, 0, 0, 22)
_v8.BackgroundTransparency = 1
_v8.Font = Enum.Font.GothamBold
_v8.TextSize = 10
_v8.Text = "Auto Color: OFF"
_v8.TextColor3 = Color3.fromRGB(231, 76, 60)
local _v9 = Instance.new("TextLabel", _v2)
_v9.Text = "Legit Body: OFF"
local _v10 = Instance.new("TextLabel", _v2)
_v10.Text = "Legit Real: OFF"
local _v11 = Instance.new("TextLabel", _v2)
_v11.Text = "Anti Ladder: OFF"
local _ = fenv.PlvP5O4pZ1d54
local _v12 = Instance.new("Frame", gui)
_v12.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
_v12.BackgroundTransparency = 0.3
_v12.Size = UDim2.new(0, 220, 0, 260)
_v12.Position = UDim2.new(0.5, -110, 0.5, -130)
_v12.Active = true
_v12.Draggable = true
local _v13 = Instance.new("UICorner", _v12)
_v13.CornerRadius = UDim.new(0, 12)
local _v14 = Instance.new("UIStroke", _v12)
_v14.Thickness = 2.5
local _v15 = Instance.new("Frame", _v12)
_v15.Size = UDim2.new(1, 0, 1, -35)
_v15.Position = UDim2.new(0, 0, 0, 35)
_v15.BackgroundTransparency = 1
local _v16 = Instance.new("UIGridLayout", _v15)
_v16.CellPadding = UDim2.new(0, 8, 0, 8)
_v16.CellSize = UDim2.new(0, 95, 0, 32)
_v16.HorizontalAlignment = Enum.HorizontalAlignment.Center
local _v17 = Instance.new("TextButton", _v15)
_v17.Text = "ON"
_v17.BackgroundColor3 = Color3.fromRGB(46, 204, 113)
_v17.Font = Enum.Font.GothamBold
_v17.TextColor3 = Color3.fromRGB(255, 255, 255)
_v17.TextSize = 10
local _v18 = Instance.new("UICorner", _v17)
_v18.CornerRadius = UDim.new(0, 8)
local _ = fenv.TviH9WsKHgBM
local _v19 = Instance.new("TextButton", _v15)
_v19.Text = "OFF"
_v19.BackgroundColor3 = Color3.fromRGB(231, 76, 60)
_v19.Font = Enum.Font.GothamBold
_v19.TextColor3 = Color3.fromRGB(255, 255, 255)
_v19.TextSize = 10
local _v20 = Instance.new("UICorner", _v19)
_v20.CornerRadius = UDim.new(0, 8)
local _v21 = Instance.new("TextButton", _v15)
_v21.Text = "Auto Seam"
_v21.BackgroundColor3 = Color3.fromRGB(44, 62, 80)
_v21.Font = Enum.Font.GothamBold
_v21.TextColor3 = Color3.fromRGB(255, 255, 255)
_v21.TextSize = 10
local _v22 = Instance.new("UICorner", _v21)
_v22.CornerRadius = UDim.new(0, 8)
local _v23 = Instance.new("TextButton", _v15)
_v23.Text = "Auto Color"
_v23.BackgroundColor3 = Color3.fromRGB(44, 62, 80)
local _v24 = Instance.new("UICorner", _v23)
local _v25 = Instance.new("TextButton", _v15)
_v25.Text = "Legit Body"
_v25.BackgroundColor3 = Color3.fromRGB(142, 68, 173)
local _v26 = Instance.new("UICorner", _v25)
local _v27 = Instance.new("TextButton", _v15)
_v27.Text = "Legit Real"
_v27.BackgroundColor3 = Color3.fromRGB(230, 126, 34)
local _v28 = Instance.new("UICorner", _v27)
local _v29 = Instance.new("TextButton", _v15)
_v29.Text = "Fix Ladder"
_v29.BackgroundColor3 = Color3.fromRGB(211, 84, 0)
local _v30 = Instance.new("UICorner", _v29)
local _v31 = Instance.new("TextButton", _v15)
_v31.Text = "+ Color"
_v31.BackgroundColor3 = Color3.fromRGB(52, 152, 219)
local _v32 = Instance.new("UICorner", _v31)
local _v33 = Instance.new("ImageButton", gui)
_v33.BackgroundTransparency = 1
_v33.Size = UDim2.new(0, 0, 0, 0)
_v33.Image = "rbxassetid://88808839781768"
_v33.Visible = false
_v33.Active = true
_v33.Draggable = true
local _v34 = Instance.new("TextButton", _v12)
_v34.Size = UDim2.new(0, 25, 0, 25)
_v34.Position = UDim2.new(1, -30, 0, 5)
_v34.BackgroundTransparency = 1
_v34.Text = "-"
_v34.TextColor3 = Color3.fromRGB(255, 255, 255)
_v34.TextSize = 25
local onClick = _v34.MouseButton1Click:Connect(function()
    local udim2 = TweenService:Create(_v12, TweenInfo.new(0.15), {BackgroundTransparency = 1, Size = UDim2.new(0, 0, 0, 0)})
    local _v35 = udim2:Play()
    task.wait(0.15)
    _v12.Visible = false
    _v33.Position = UDim2.new(0, (_v12.Position.X.Offset + 80), 0, (_v12.Position.Y.Offset + 100))
    _v33.Visible = true
    local udim2 = _v33:TweenSize(UDim2.new(0, 60, 0, 60), "Out", "Back", 0.15, true)
    local _ = fenv.SjhhOK2JriGPD
end)
local onClick = _v33.MouseButton1Click:Connect(function()
    local udim2 = _v33:TweenSize(UDim2.new(0, 0, 0, 0), "In", "Quad", 0.1, true)
    task.wait(0.1)
    _v33.Visible = false
    _v12.Position = UDim2.new(0, (_v33.Position.X.Offset - 80), 0, (_v33.Position.Y.Offset - 100))
    _v12.Visible = true
    local udim2 = TweenService:Create(_v12, TweenInfo.new(0.15, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {BackgroundTransparency = 0.3, Size = UDim2.new(0, 220, 0, 260)})
    local _v36 = udim2:Play()
    local _ = fenv.J9Xv8sOH2VEJX
end)
local onClick = _v17.MouseButton1Click:Connect(function()
    _v6.Text = "WallHop: ON"
    _v6.TextColor3 = Color3.fromRGB(46, 204, 113)
    _v7.Text = "Auto Seam: OFF"
    _v7.TextColor3 = Color3.fromRGB(231, 76, 60)
    _v8.Text = "Auto Color: OFF"
    _v8.TextColor3 = Color3.fromRGB(231, 76, 60)
    _v9.Text = "Legit Body: OFF"
    _v9.TextColor3 = Color3.fromRGB(231, 76, 60)
    _v10.Text = "Legit Real: OFF"
    _v11.Text = "Anti Ladder: OFF"
    local _ = fenv.F21FlEDich9UT
    local _ = fenv.ORmOnqCJhtLJDE
end)
local onClick = _v19.MouseButton1Click:Connect(function()
    _v6.Text = "WallHop: OFF"
    _v7.Text = "Auto Seam: OFF"
    _v8.Text = "Auto Color: OFF"
    _v9.Text = "Legit Body: OFF"
    _v10.Text = "Legit Real: OFF"
    _v11.Text = "Anti Ladder: OFF"
    local _ = fenv.j0MvCOt0rC6goV
end)
local onClick = _v21.MouseButton1Click:Connect(function()
    _v6.Text = "WallHop: OFF"
    _v7.Text = "Auto Seam: ON"
    _v7.TextColor3 = Color3.fromRGB(46, 204, 113)
    _v8.Text = "Auto Color: OFF"
    _v9.Text = "Legit Body: OFF"
    _v10.Text = "Legit Real: OFF"
    _v11.Text = "Anti Ladder: OFF"
    local _ = fenv.vwdiKWdmiM3h
end)
local onClick = _v23.MouseButton1Click:Connect(function()
    _v6.Text = "WallHop: OFF"
    _v7.Text = "Auto Seam: ON"
    _v7.TextColor3 = Color3.fromRGB(46, 204, 113)
    _v8.Text = "Auto Color: ON"
    _v8.TextColor3 = Color3.fromRGB(46, 204, 113)
    _v9.Text = "Legit Body: OFF"
    _v10.Text = "Legit Real: OFF"
    _v11.Text = "Anti Ladder: OFF"
    local _ = fenv.Hm2Q97meLxk1i
end)
local onClick = _v29.MouseButton1Click:Connect(function()
    _v6.Text = "WallHop: OFF"
    _v7.Text = "Auto Seam: ON"
    _v7.TextColor3 = Color3.fromRGB(46, 204, 113)
    _v8.Text = "Auto Color: ON"
    _v9.Text = "Legit Body: OFF"
    _v10.Text = "Legit Real: OFF"
    _v11.Text = "Anti Ladder: ON"
    local _ = fenv.QTYOs8CAtAEx
end)
local onClick = _v25.MouseButton1Click:Connect(function()
    _v6.Text = "WallHop: OFF"
    _v7.Text = "Auto Seam: ON"
    _v8.Text = "Auto Color: ON"
    _v9.Text = "Legit Body: ON"
    _v10.Text = "Legit Real: OFF"
    _v11.Text = "Anti Ladder: ON"
    local _ = fenv.LxQGZEvtZfsNJ
end)
local onClick = _v27.MouseButton1Click:Connect(function()
    _v6.Text = "WallHop: OFF"
    _v7.Text = "Auto Seam: ON"
    _v8.Text = "Auto Color: ON"
    _v9.Text = "Legit Body: OFF"
    _v10.Text = "Legit Real: ON"
    _v11.Text = "Anti Ladder: ON"
    local _ = fenv.c9P7rpmbnEgl57
end)
local onClick = _v31.MouseButton1Click:Connect(function()
    _v31.Text = "Pick..."
    local onButton1Down = _v1.Button1Down:Connect(function(...) end)
    local _ = fenv.oLOUsVMyLEWz
end)
local onHeartbeat = RunService.Heartbeat:Connect(function(deltaTime)
    local _ = fenv.E4pzeCcssLzaeR
end)
local onJumpRequest = UserInputService.JumpRequest:Connect(function(...)
    local _ = fenv.JoGWSzJ65GbK
end)